### ISSUE TITLE
Game can be played with a blank username?

### ISSUE THREAD

**Issue by ghost** [teohhanhui/paper-chess#1]
I think the player usernames should default to like Player 1 or Player 2 if they messed up or re-prompt them to enter something.

![Screenshot_2019-08-18_14-16-58](https://user-images.githubusercontent.com/24475030/63220898-2a103700-c1c3-11e9-8717-2f54415df6ce.png)
![t](https://user-images.githubusercontent.com/24475030/63220923-a4d95200-c1c3-11e9-9894-6a61615f3d8c.png)
![Screenshot_2019-08-18_14-17-59](https://user-images.githubusercontent.com/24475030/63220900-309eae80-c1c3-11e9-9488-8f2b58093c44.png)

I think I wanna implement either of those mechanisms. What do you think @teohhanhui?

**Comment by teohhanhui** [comment]
Yeah, let's fallback to `Player n`.
